<div class="container">
    <div class="row">
        <h2 class="h2 col-xs-12"><?php $titlePage; ?></h2>
    </div>
    <div class="row">
        <?php require __DIR__.'/../alerts/_success.phtml'; ?>
        <?php require __DIR__.'/../alerts/_errors.phtml'; ?>
    </div>
    <div class="row">
        <div class="col-xs-12 col-xs-offset-0 col-md-8 col-md-offset-2">
            <h1 class="h1 text-center">E-maileiro</h1>
            <p>
                Seja bem vindo a esta aplicacao mini
            </p>
            
        </div>
    </div>
</div>