version: '2'

services:
  mysql:
    image: mariadb:latest
    container_name: mysql-on-hand
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD="testes"
      - MYSQL_DATABASE="hand_admin"
      - MYSQL_USER="sandbox"
      - MYSQL_PASSWORD="sandbox"
      - MYSQL_ROOT_HOST="%"
      - MYSQL_HOST="localhost"
      - API_CONSUMER_KEY="ddb0a85e591fd863e45a2d656ceffaee05c2361bc"
      - API_CONSUMER_SECRET="5e27e0cc96e9dad4f85b6b587b424cb2"
      - API_TOKEN="c5ba1a609bca56bc26586af478596b7405c23621f"
      - API_TOKEN_SECRET="ac8a208e8e933eaf891c742cee990607"
      - API_BASE_URL="https://api.mediapost.com.br"
      
  php:
    build:
      context: ./docker/php7-fpm
    image: laravel:php-fpm
    container_name: php-on-hand
    depends_on:
      - mysql
    command: bash -c "php-fpm  && php-fpm -v"
    environment:
      DB_PORT: 3306
      DB_USERNAME: sandbox
      DB_PASSWORD: sandbox
      DB_ROOT_USERNAME: root
      DB_ROOT_PASSWORD: testes
      DB_DATABASE: hand_admin
      DB_HOST: mysql
      MYSQL_HOST: mysql
      REDIS_HOST: redis
      DEBUG: 1
      
    links:
      - mysql
    volumes:
      - ./app/:/var/www/html:rw

  web:
    image: nginx:alpine
    container_name: nginx-on-hand
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
    ports:
      - 4001:4001

volumes:
  mysql-data:
    driver: "local"