<div class="container">
    <div class="row">
        <?php if($auth->can('create-message')): ?>
            <a href="#" onclick="newContactByList()" class='btn btn-primary'>Nova Mensagem</a>
        <?php endif;?>
        <table class="table" id="list_of_messages" style="width:100%;">   
            <thead>
                <tr>
                    <th style="text-align: center;">Código</th>
                    <th style="text-align: center;">Assunto</th>
                    <th style="text-align: center;">Status</th>
                    <th style="text-align: center;">Ações</th>
                    </tr>
            </thead>
        </table>
    </div>
</div>

<script>
$(document).ready(function() {
    $.fn.dataTable.ext.errMode = 'none';
    $('#list_of_messages').DataTable( { 
        "processing": true,
        "serverSide": true,
        "paging": false,
        "filter": false,
        "info": false,
        "scrollY": "600px",
        "scrollCollapse": true,
        "ajax":{
                url: "/api/v1/messages",
                type: "GET",
                headers: { 'Authorization': 'Bearer <?php echo $auth->getApiToken();?>' },
                
            },
        "columns": [
                    { "data": "code" },
                    { "data": "subject" },
                    { "data": "status" },
                    {
                    sortable: false,
                        "render": function ( data, type, full, meta ) {
                            var buttonID = "rollover_"+full.code;
                            return  '<a id='+buttonID+' onclick="inviteMessage('+full.code+')" class="btn btn-success fa " role="button">Enviar Mensagem</a> \
                                     <a id='+buttonID+' onclick="showResults('+full.code+')" class="btn btn-success fa " role="button">Ver Resultados</a>';
                        }
                    }
                ]
         } )
    } );
    
    inviteMessage = function(codList)
    {
        $.fn.dataTable.ext.errMode = 'none';
        $.ajax({
                type: "GET",
                url: "/message/"+codList+"/send",
                data: {},
                success: function(response)
                {
                    openModalWindow( 700 , 400 , "Enviar Mensagem" , response )
                },
                error: function(jqXHR, textStatus, errorThrown){
                   returnErr = JSON.parse(jqXHR.responseText)
                   messageError = str_replace_recursive( "\n",'<br />',returnErr.message)
                   errorDialog( 410 , 300 , messageError )
                }
        });
    }
    
    newContactByList = function()
    {
        $.fn.dataTable.ext.errMode = 'none';
        $.ajax({
                type: "GET",
                url: "/message/new",
                data: {},
                success: function(response)
                {
                    openModalWindow( 500 , 600 , "Nova Mensagem" , response )
                },
                error: function(jqXHR, textStatus, errorThrown){
                   returnErr = JSON.parse(jqXHR.responseText)
                   messageError = str_replace_recursive( "\n",'<br />',returnErr.message)
                   errorDialog( 410 , 300 , messageError )
                }
        });
    }
    
    showResults = function(codList)
    {
        $.ajax({
                type: "GET",
                url: "/message/"+codList+"/show-results",
                data: {},
                success: function(response)
                {
                    openModalWindow( 800 , 700 , "Resultados do Envio" , response )
                },
                error: function(jqXHR, textStatus, errorThrown){
                   returnErr = JSON.parse(jqXHR.responseText)
                   messageError = str_replace_recursive( "\n",'<br />',returnErr.message)
                   errorDialog( 410 , 300 , messageError )
                }
        });
    }

</script>